name: tbv-v0
channels:
  # for priority order, we prefer pytorch as the highest priority as it supplies
  # latest stable packages for numerous deep learning based methods. conda-forge
  # supplies higher versions of packages like opencv compared to the defaults
  # channel.
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # python essentials
  - python>=3.8
  - pip
  # formatting and dev environment
  - black
  - coverage
  - flake8
  - mypy
  - pylint
  - pytest
  # dask and related
  - dask # same as dask[complete] pip distribution
  - python-graphviz
  # core functionality and APIs
  - matplotlib>=3.4.2
  - networkx
  - numpy
  - pandas
  - pillow>=8.0.1
  - scikit-learn
  - hydra-core
  # 3rd party algorithms for different modules
  - captum
  - cudatoolkit=11.3
  - mapbox_earcut
  - opencv # preferring conda-forge's distribution as it provides the latest distribution
  - pytorch
  - shapely
  - torchvision
  - trimesh
  # io
  - h5py
  - plotly>=4.14.3
  - tabulate
  - imageio
  - pip:
    - av2==0.1.0
    - omegaconf
    - open3d>=0.13.0
    - scipy>=1.6.0
