name: tbv-v0
channels:
  # for priority order, we prefer pytorch as the highest priority as it supplies
  # latest stable packages for numerous deep learning based methods. conda-forge
  # supplies higher versions of packages like opencv compared to the defaults
  # channel.
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # python essentials
  - python=3.8
  - pip
  # formatting and dev environment
  - black
  - coverage
  - mypy
  - pylint
  - pytest
  - flake8
  # dask and related
  - dask # same as dask[complete] pip distribution
  - python-graphviz
  # core functionality and APIs
  - matplotlib==3.4.2
  - networkx
  - numpy
  - nodejs
  - pandas
  - pillow>=8.0.1
  - scikit-learn
  # 3rd party algorithms for different modules
  - cudatoolkit=10.2
  - opencv # preferring conda-forge's distribution as it provides the latest distribution
  - pytorch
  - torchvision
  - hydra-core
  - captum
  - mapbox_earcut
  - trimesh
  # io
  - h5py
  - plotly=4.14.3
  - tabulate
  - imageio
  - pip:
    - pydegensac
    - argoverse @ git+https://github.com/argoai/argoverse-api.git@master
    - open3d==0.13.0
    - mseg @ git+https://github.com/mseg-dataset/mseg-api.git@master
    - omegaconf
    - scipy>=1.6.0
