


BevRenderingConfig:

    _target_: tbv.rendering_config.BevRenderingConfig
    num_processes: 1

    # Hyperparameters
    render_vector_map_only: False
    render_reflectance: False
    recompute_segmentation: False
    projection_method: ray_tracing

    dilation: 20 # 20 m in all directions

    # tbv_dataroot: /Users/jlambert/Downloads/TbV_v0.1
    # rendered_dataset_dir: /Users/jlambert/Downloads/TbV_v0.1/rendered_egoview_2021_09_03

    tbv_dataroot: /home/jlambert/TbV_v0.1
    rendered_dataset_dir: /home/jlambert/TbV_v0.1/rendered_bev_2021_09_04

    render_test_set_only: True
    jitter_vector_map: True
    max_dist_to_del_crosswalk: 15 # meters, augmentation will abort if not found in range
    delete_log_after_rendering: False
    viewpoint: bev

    use_histogram_matching: False
    make_bev_semantic_img: False # whether to render RGB or semantics in BEV
    render_reflectance_only: False
    filter_ground_with_semantics: False # quite expensive
    filter_ground_with_map: True # using ground height
    max_ground_mesh_range_m: 25 # trace rays to triangles up to 20 m away
    resolution: 0.02 # meters/pixel
    use_median_filter: False
    semantic_img_interp_type: # nearest # linear for rgb, but nearest for label map
    sensor_img_interp_type: linear # linear for rgb, but nearest for label map


