EgoviewRenderingConfig:

  _target_: tbv.rendering_config.EgoviewRenderingConfig

  use_depth_map_for_occlusion: True

  num_processes: 1
  render_reflectance: False
  recompute_segmentation: False

  range_m: 20  # 20 m in all directions

  tbv_dataroot: /Users/johnlambert/Downloads/tbv_dataset/logs
  rendered_dataset_dir: /Users/johnlambert/Downloads/tbv_dataset/rendered_egoview_2022_03_29
  seamseg_output_dataroot: /Users/johnlambert/Downloads/tbv_dataset/seamseg_output

  render_test_set_only: False
  jitter_vector_map: True
  max_dist_to_del_crosswalk: 15 # meters, augmentation will abort if not found in range
